// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfvuynrpquvxpnddtdwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdnV5bnJwcXV2eHBuZGR0ZHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTUyMjUsImV4cCI6MjA2OTc3MTIyNX0.dUE1iRy_Up9P1viz9PMdi8JFHbn-HFr7erK-ELLd0IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});